services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./localhost.crt:/etc/nginx/certs/localhost.crt:ro
      - ./localhost.key:/etc/nginx/certs/localhost.key:ro
      - ./php-app/app:/var/www/html
    depends_on:
      - php
      - dotnet
      - redis
    networks:
      - app-network

  php:
    build:
      context: ./php-app
      dockerfile: Dockerfile
    volumes:
      - ./php-app/app:/var/www/html
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  dotnet:
    build:
      context: ./dotnet-app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
